name: CI/CD

on:
    pull_request:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci-cd:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.1.32

            - name: Install dependencies
              run: bun install

            - name: Run CI
              run: bun run ci

            - name: Creating .npmrc
              run: |
                  cat << EOF > "$HOME/.npmrc"
                    //registry.npmjs.org/:_authToken=$NPM_TOKEN
                  EOF
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: bun run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
